name: Build deb packages

on:
  push:
  workflow_dispatch:

jobs:
  build_deb:
    strategy:
      matrix:
        ros_distribution:
          - humble
          - jazzy
          - rolling
        package_name:
          - rclcpp
          - rclcpp_action
          - rclcpp_components
          - rclcpp_lifecycle
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          # https://docs.ros.org/en/humble/How-To-Guides/Building-a-Custom-Deb-Package.html#install-dependencies
          apt-get install -y python3-bloom python3-rosdep fakeroot debhelper dh-python
      - name: Build ${{ matrix.package_name }} for ${{ matrix.ros_distribution }}
        run: |
          rosdep update
          rosdep install -y --ignore-src --from-paths ${{ matrix.package_name }}
          cd ${{ matrix.package_name }}
          bloom-generate rosdebian
          fakeroot debian/rules binary
      - name: Find deb package
        id: find_deb
        run: |
          echo "deb_package=$(find . -name '*.deb' | head -n 1)" >> $GITHUB_OUTPUT
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.find_deb.outputs.deb_package }}
